# Generated by Django 4.2.6 on 2023-10-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="question",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("ques", models.CharField(max_length=210)),
                ("quesTime", models.DateTimeField(auto_now_add=True)),
                ("ans", models.CharField(max_length=600)),
                ("ansTime", models.DateTimeField()),
                ("display", models.BooleanField(default=True)),
            ],
        ),
    ]
