# Generated by Django 4.2.6 on 2023-10-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulbox", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="ansTime",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="question",
            name="quesTime",
            field=models.IntegerField(),
        ),
    ]
