# Generated by Django 4.2.6 on 2023-10-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulbox", "0002_alter_question_anstime_alter_question_questime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="ans",
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="ansTime",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="quesTime",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
