# Generated by Django 4.2.6 on 2023-10-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulbox", "0003_alter_question_ans_alter_question_anstime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="quesTime",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
