# Generated by Django 4.2.6 on 2023-10-07 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulbox", "0004_alter_question_questime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="quesTime",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 7, 21, 34, 33, 919049)
            ),
        ),
    ]
