# Generated by Django 4.2.6 on 2023-10-07 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulbox", "0005_alter_question_questime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="quesTime",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 7, 21, 36, 2, 541109)
            ),
        ),
    ]
