# Generated by Django 4.2.4 on 2023-10-11 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulbox", "0006_alter_question_id_alter_question_questime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="quesTime",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 11, 9, 12, 28, 410324)
            ),
        ),
    ]
