# Generated by Django 4.2.4 on 2023-10-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulbox", "0007_alter_question_questime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="quesTime",
            field=models.DateTimeField(null=True),
        ),
    ]
