# Generated by Django 4.2.4 on 2023-10-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulbox", "0008_alter_question_questime"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quesNum", models.IntegerField()),
                ("content", models.CharField(max_length=2000)),
                ("subTime", models.DateTimeField(null=True)),
                ("display", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="IWanna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ques", models.CharField(max_length=300)),
                ("quesTime", models.DateTimeField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="question",
            name="ans",
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="ques",
            field=models.CharField(max_length=300),
        ),
    ]
